title = "config"
host = "10.0.0.75:8080"
key = "/home/kepuss/key.pem"
cert = "/home/kepuss/cert.pem"

username = "mkepkowski"
password = "pot12ter"

loglevel = "debug"


[registerSiteRequestParams]
opHost = "https://gluuserver"
authorizationRedirectUri = "https://10.0.0.250:8080/redirect"
postLogoutRedirectUri = "https://10.0.0.250:8080/logout"

redirectUris = []
responseTypes = ["code"]

clientId = ""
clientSecret = ""
clientName = ""
clientJwksUri = ""
clientTokenEndpointAuthMethod = ""
clientRequestUris  = []
clientLogoutUri  = []
clientSectorIdentifierUri = ""

scope = ["openid", "profile"]
uiLocales  = []
claimsLocales  = []
acrValues = []
grantType = ["authorization_code"]
contacts = ["example@example.com"]


[authorizationCodeFlowRequestParams]
clientId = "@!BB85.C095.8C1E.0573!0001!F554.249C!0008!213A.710A"
clientSecret = ""
userId =""
userSecret =""
scope = "openid"
acr = ""
nonce = "15d3ltbdd65b1o9at1q5gjq3ge"
authorizationRedirectUri = "https://10.0.0.250:8080/redirect"
