title = "config"
host = "oxd.example.com:8099"
idpHost="https://idp.example.com"
key = "src/oxd-client-demo/conf/tls/key.pem"
cert = "src/oxd-client-demo/conf/tls/cert.pem"



username = "test_user"
password = "test_user_password"

clientId="@!E77D.AB59.5C1D.D971!0001!EAFB.EC9C!0008!8EF1.EB4C.BEF4.BEA1"
clientSecret="zaq1@WSX"
clientRegistrationClientUri="https://idp.example.com/identity/"
type="REST"
oxdHttpsHost="https://oxd.example.com:8443"
loglevel = "debug"

[uma]
checkAccessPath="/test"
checkAccessMethod="GET"
[[uma.resources]]
path="/test"
[[uma.resources.conditions]]
httpMethods=["GET"]
scopes=["http://photoz.example.com/dev/actions/view"]

[[uma.resources.conditions]]
httpMethods=["PUT", "POST"]
scopes=["http://photoz.example.com/dev/actions/all","http://photoz.example.com/dev/actions/add"]
ticketScopes=["http://photoz.example.com/dev/actions/add"]

[[uma.resources.conditions]]
httpMethods=["DELETE"]
scopes=["http://photoz.example.com/dev/actions/all","http://photoz.example.com/dev/actions/remove"]
ticketScopes=["http://photoz.example.com/dev/actions/remove"]




[registerSiteParams]

opHost = "https://idp.example.com"
authorizationRedirectUri = "https://client.example.com:8080/redirect"
postLogoutRedirectUri = "https://client.example.com:8080/"

redirectUris = ["https://client.example.com:8080/redirect"]
responseTypes = ["code"]


clientId="@!E77D.AB59.5C1D.D971!0001!EAFB.EC9C!0008!8EF1.EB4C.BEF4.BEA1"
clientSecret="zaq1@WSX"
clientName = ""
clientJwksUri = ""
clientTokenEndpointAuthMethod = ""
clientRequestUris  = []
clientLogoutUri  = []
clientSectorIdentifierUri = ""

scope = ["openid", "profile", "uma_protection", "uma_authorization"]
uiLocales  = []
claimsLocales  = []
claimsRedirectUri = ["https://client.example.com:8080/claimsRedirect"]
acrValues = []
grantType = ["authorization_code"]
contacts = ["example@example.com"]




