title = "config"
host = "10.0.0.75:8080"

[registerSiteRequestParams]
opHost = "https://gluuserver"
authorizationRedirectUri = "https://10.0.0.250/redirect"
postLogoutRedirectUri = "https://10.0.0.250/logout"

redirectUris = []
responseTypes = ["code"]

clientId = ""
clientSecret = ""
clientName = ""
clientJwksUri = ""
clientTokenEndpointAuthMethod = ""
clientRequestUris  = []
clientLogoutUri  = []
clientSectorIdentifierUri = ""

scope = ["openid"]
uiLocales  = []
claimsLocales  = []
acrValues = []
grantType = ["authorization_code"]
contacts = ["example@example.com"]


[updateSiteRequestParams]
oxdId = "46099f43-7f66-4302-8c2f-7cf802722949"
opHost = "https://gluuserver"
authorizationRedirectUri = "https://10.0.0.250/redirect"
postLogoutRedirectUri = "https://10.0.0.250/logout"

scope = ["openid", "profile"]

[authorizationUrlRequestParams]
OxdId = "46099f43-7f66-4302-8c2f-7cf802722949"
Scope = ["openid"]
AcrValues = []
Prompt = ""

[authorizationCodeRequestParams]
OxdId = "46099f43-7f66-4302-8c2f-7cf802722949"
RedirectUrl = "https://10.0.0.250/redirect"
ClientId = ""
ClientSecret = ""
UserId = ""
UserSecret = ""
Scope = ["openid"]
Nonce = ""
Acr = ""