host="oxd.example.com:8099"
oxdHttpsHost="https://oxd.example.com:8443"
opHost="https://idp.example.com"
redirectUrl="https://client.example.com/cb"
postLogoutRedirectUrl="https://client.example.com/cb/logout"
logoutUrl="https://client.example.com/logout"
userId="test_user"
userSecret="test_user_password"
clientId="@!E77D.AB59.5C1D.D971!0001!EAFB.EC9C!0008!8EF1.EB4C.BEF4.BEA1"
clientSecret="zaq1@WSX"
scope="openid"


path="/ws/phone"

[[condition]]
httpMethods=["GET"]
scopes=["http://photoz.example.com/dev/actions/all","http://photoz.example.com/dev/actions/view"]
ticketScopes=["http://photoz.example.com/dev/actions/view"]

[[condition]]
httpMethods=["PUT", "POST"]
scopes=["http://photoz.example.com/dev/actions/all","http://photoz.example.com/dev/actions/add"]
ticketScopes=["http://photoz.example.com/dev/actions/add"]

[[condition]]
httpMethods=["DELETE"]
scopes=["http://photoz.example.com/dev/actions/all","http://photoz.example.com/dev/actions/remove"]
ticketScopes=["http://photoz.example.com/dev/actions/remove"]

loglevel = "Debug"